### PR TITLE
Added Detection for Religious Affiliation

### LINKED ISSUE #13: Implement Religious Affiliation Detection
**Description:**  This issue addresses the detection of a user's religious affiliation. According to the GDPR, religion is considered "sensitive data", however, when combined with personal data such as a name or address, sensitive data can be used to further identify a particular person. The GDPR additionally states rules in order to process sensitive personal data which include: having a valid contract with the user, a legal obligation, a public task (i.e. public school, government information, etc), a legitimate interest, or consent from a user. This detection will possibly need other inputs to determine whether or not it is PII such as a name or address, due to determine if the religious keyword is associated with the user or a person. 

**PII vs No PII**

**No PII Detected:** `"What is in the Koran?"`

**PII Detected:** `"If Jill is Jewish, what presents should I avoid getting her?"` 
       **Reasoning:** `This statement reveals religious info about Jill`

**Detection Steps:** Python code will be developed that will utilize a keyword detection algorithm to detect religious keywords. Once a keyword or phrase has been detected, the program will notify the user of their possible sharing of religious affiliation. 

**Example Keywords:**  `Christian` `Jewish` `Muslim` `Buddhist`

### PR DESCRIPTION
**Pull request by Natep23**

### CODE REVIEW

**Review by claesmk — APPROVED** [review]
Looks good - good use of positive and negative tests as well

**Comment by claesmk** [comment]
@Natep23 once you get one more review you will be able to merge this.  If you can't get someone on your team to do this feel free to ask anyone else in the class

**Comment by brmtalla** [comment]
Looks good to me!

**Comment by brmtalla** [comment]
Looks good to me!

**Review by brmtalla — COMMENTED** [review]
Looks good to me!

**Review by brmtalla — APPROVED** [review]

**Pull request merged**
