### PR TITLE
added detection for US drivers license

### LINKED ISSUE #32: Implement Drivers License Detection
Description: A driver's license typically contains the holder's personal information, including their full name, date of birth, address, and photograph. It also includes essential details such as the license number, issue and expiration dates, and any specific restrictions or endorsements. It proves that the holder has completed the necessary requirements, such as passing a driving test and meeting exact age and medical criteria, to drive a car, motorcycle, or other motorized vehicle. They are generally required to be carried by drivers while operating a vehicle.

Format: Driver's licenses are commonly used as a form of identification, and they vary in appearance and format depending on the country or state issuing them. Including name, DOB, expiration date, and ID number

Example: 
Nadir Miller 
03/18/2001
03/18/2040
000012345678

Detection Steps: Look for Holograms and Security Features: Many driver's licenses include holographic elements, such as holographic overlays, holographic images, or microprinting. Check for Watermarks: Hold the license up to a light source and look for watermarks or embedded images. Validate Security Features with a Light Source: Some licenses have additional security features that are visible under ultraviolet (UV) light.

### PR DESCRIPTION
**Pull request by nsmiller1**

### CODE REVIEW

**Review by claesmk — CHANGES_REQUESTED** [review]
Your test cases are failing because you are not attempting to find a driver's license.  If you look at the [entity description](https://microsoft.github.io/presidio/supported_entities/) for a driver's license it links you to the NTSI driver's license formats.

If you try a test case like this:

```
        results = analyze_text('005544332211')
        print(results)
        self.assertIn('US_DRIVER_LICENSE', str(results))
```

You'd see that the analyzer does detect a possible US_DRIVER_LICENSE and the test case would pass, however, the score is very low (0.01)

> [type: US_BANK_NUMBER, start: 0, end: 12, score: 0.05, type: US_DRIVER_LICENSE, start: 0, end: 12, score: 0.01]

If you add some context to the numbers:

```
        results = analyze_text('lic# 005544332211')
        print(results)
        self.assertIn('US_DRIVER_LICENSE', str(results))
```

You can see that the score improves significantly (0.4) and is now higher than a US_BANK_NUMBER, which is another valid possibility.  

>[type: US_DRIVER_LICENSE, start: 5, end: 17, score: 0.4, type: US_BANK_NUMBER, start: 5, end: 17, score: 0.05]

Detecting multiple entities is often expected and is discussed [here](https://microsoft.github.io/presidio/faq/#what-can-i-do-if-presidio-falsely-detects-text-as-pii-entities-false-positives).  This is why we use the self.assertIn() method to look for AT LEAST the target entity.  If there are more it's OK.

You scan see the specific context works by looking at the related [code](https://github.com/microsoft/presidio/blob/a1c8a23e206f1a5671f164758a4d14b769901fd4/presidio-analyzer/presidio_analyzer/predefined_recognizers/us_driver_license_recognizer.py#L45) 

You need to re-structure your test case to look for both valid and invalid driver's license strings.

**Review by claesmk — APPROVED** [review]
Looks good

**Comment by claesmk** [comment]
@aalston2 this is waiting on your code review

**Review by daseanneclos — COMMENTED** [review]
Looks good!

**Review by daseanneclos — APPROVED** [review]
Everything is good!

**Comment by claesmk** [comment]
@nsmiller1 you can merge this pull request now

**Pull request merged**
