### PR TITLE
Added detection for credit card number

### LINKED ISSUE #6: Implement Credit Card Number Detection
**Description**

ChatGPT is a powerful language model capable of generating human-like responses to user inputs. However, there is a risk that the model might inadvertently generate or extract credit card numbers from the user's input, which could pose a significant security and privacy concern. To ensure the protection of user information, it is essential to implement measures that prevent the detection and propagation of credit card numbers by ChatGPT. There is a concern regarding the potential risk of Credit Card Number (CCN) detection when using the platform. This issue aims to address this concern by implementing a reliable mechanism to prevent the accidental exposure of sensitive credit card information during conversations with ChatGPT.

For example:
> 4444-5555-6666-7777

**Detection Steps**
The proposed solution involves integrating a credit card number detection mechanism using Python. This mechanism will analyze user inputs in real-time, identifying and filtering out any credit card numbers before they are processed by the language model. The detection mechanism can be implemented by designing code for this purpose that detects a 16 digit number, reads the first 6 numbers and rejects its implementation into returning a response if they match a Bank Identification Number.

### PR DESCRIPTION
**Pull request by brmtalla**

### CODE REVIEW

**Review by Natep23 — APPROVED** [review]
Seems fine to me.

**Review by claesmk — CHANGES_REQUESTED** [review]
I think you should be using the CREDIT_CARD entity?

**Comment by brmtalla** [comment]
> I think you should be using the CREDIT_CARD entity?

I tried that at first, but would get the error "'CREDIT_CARD' not found in '[type: US_BANK_NUMBER, start: 0, end: 16, score: 0.05, type: US_DRIVER_LICENSE, start: 0, end: 16, score: 0.01]", so I don't think that's an entity I can use.

**Comment by claesmk** [comment]
The issue here is that your cc numbers in your test cases do not look like potentially valid credit card numbers.  Even the example you included in your issue does not get detected because it does not pass the validation steps that Microsoft has chosen to implement. 

Usually the easiest way to determine what's going wrong is to look at the underlying [source code](https://github.com/microsoft/presidio/blob/main/presidio-analyzer/presidio_analyzer/predefined_recognizers/credit_card_recognizer.py) that is responsible for the detection.  

There are multiple sources which document some example credit card numbers.  Square's developer [documentation](https://developer.squareup.com/docs/devtools/sandbox/payments) is a good choice.

From that you could construct a test case that looks something like this:
```
    def test_cc_number_detection(self):
        # test a (possibly) valid credit card number
        # https://developer.squareup.com/docs/devtools/sandbox/payments
        cc_nums = {'Visa': '4111 1111 1111 1111',
                   'Mastercard': '5105 1051 0510 5100',
                   'Discover': '6011 0000 0000 0004',
                   'Diners Club': '3000 000000 0004',
                   'JCB': '3566 1111 1111 1113',
                   'American Express': '3400 000000 00009'}

        for cc_type, cc_num in cc_nums.items():
            print('testing {} number: {}'.format(cc_type, cc_num))
            results = analyze_text(cc_num)
            print(results)
            self.assertIn('CREDIT_CARD', str(results))

        # test an invalid credit card number
        results = analyze_text('1234 5678 9012 3456')
        self.assertNotIn('CREDIT_CARD', str(results))
```

Using predefined sample credit card numbers is superior to trying to make them up on your own.  If you make up a number it's possible you could make a lucky guess and actually use someone's real credit card number.  Even though the number without an expiration date or validation pin is generally useless, you wouldn't want a real number in your source code.

**Review by claesmk — APPROVED** [review]
Looks good - I think this is more in-line with what you were trying to achieve in your requirements description.

**Comment by claesmk** [comment]
@brmtalla this looks ready for you to merge and delete your branch & Codespaces

**Pull request merged**
