### PR TITLE
Added detection for social security

### LINKED ISSUE #4: Implement Social Security Number Detection
**Description:** 
Detecting and protecting a social security number (SSN) is of utmost importance due to its critical role in personal identification and the potential for severe consequences if it falls into the wrong hands. You use your social security number for so many everyday tasks including identity verification, preventing identity theft, maintaining financial security, preventing medical identity theft, combating government benefits fraud, facilitating legal processes, and preserving personal privacy. Safeguarding this unique identifier helps individuals protect their personal and financial well-being, ensuring they have control over their identity and reducing the risks associated with unauthorized access to their personal information.

For example:

`111-11-1111`

**Detection Steps:**
Python code will be developed which will detect a string that will match a valid social security format. This code will check to if the social security consists of any 3 combination of numbers following a hyphen followed by any pair of numbers following a hyphen ended by any 4 combination of numbers.

### PR DESCRIPTION
**Pull request by natalyapolite1**

### CODE REVIEW

**Review by claesmk — CHANGES_REQUESTED** [review]
Are you 100% sure that none of the test social security numbers are potentially real?  At a glance it looks like some fall within valid ranges.  Per the [comment](https://github.com/NCATComp410/comp410_summer_2023/issues/4#issuecomment-1580324871) I left in the issue please make sure you've scrubbed this to be sure you don't accidentally have a valid number.

**Comment by claesmk** [comment]
I'm also not clear on how test_political_group_detection() got removed, it will need to be added back

**Comment by natalyapolite1** [comment]
> I'm also not clear on how test_political_group_detection() got removed, it will need to be added back

When trying to commit, I am receiving errors. I am not sure what the issue is now.

**Review by ncholliday — APPROVED** [review]

**Review by adomakk — APPROVED** [review]

**Comment by natalyapolite1** [comment]
@claesmk I have updated the positive test cases. I am unable to move forward in completing the assignment until the change review has been approved.

**Comment by claesmk** [comment]
Somehow you managed to delete [test_name_detection](https://github.com/NCATComp410/comp410_summer_2023/blob/6a80fe8f1a19d548e2674973a26e010e23b3bec5/test_pii_scan.py#L41) and also revert the "results" type-o from [test_phone_number_detection](https://github.com/NCATComp410/comp410_summer_2023/blob/6a80fe8f1a19d548e2674973a26e010e23b3bec5/test_pii_scan.py#L112).  I'm not clear how this happened.  Last night I merged main into your branch for you.  Your initial [commit](https://github.com/NCATComp410/comp410_summer_2023/pull/20/commits/623fc7f5aaf777e2531f1a5f25eed0beec7a5665) changed a couple of ssn test cases, however, your final [commit](https://github.com/NCATComp410/comp410_summer_2023/pull/20/commits/605276e7e69234e1337d9e24cc06437db9c071df) caused the aforementioned issue.  

I'll fix this for you and commit

**Review by claesmk — APPROVED** [review]
Corrected issues looks OK now

**Pull request merged**
